# Generated by Django 5.2.1 on 2026-02-12 07:34

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt_people', models.CharField(max_length=50, verbose_name='Кол-во человек в команде')),
                ('cnt_year', models.CharField(max_length=50, verbose_name='Кол-во лет работы в сфере')),
                ('cnt_square', models.CharField(max_length=50, verbose_name='Кол-во кв.метров чистки')),
                ('cnt_reviews', models.CharField(default='25 000', help_text="Число на странице 'О компании' в подзаголовке 'довольными остались свыше 25 000 человек!'", max_length=50, verbose_name='Кол-во положительных отзывов')),
                ('cnt_order', models.IntegerField(default='960', verbose_name='Кол-во выполненных заказов')),
                ('clients', models.IntegerField(default='98', verbose_name='Сколько процентов клиентов приходят по рекомендации')),
            ],
            options={
                'verbose_name': 'Статистика о компании',
                'verbose_name_plural': 'Статистика о компании',
            },
        ),
        migrations.CreateModel(
            name='AdditionalServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150, verbose_name='Название дополнительной услуги')),
                ('desc', models.TextField(max_length=150, verbose_name='Описание дополнительной услуги')),
            ],
            options={
                'verbose_name': 'Дополнительная услуга',
                'verbose_name_plural': 'Дополнительные услуги',
            },
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_account', models.CharField(blank=True, max_length=100, verbose_name='Расчётный счёт')),
                ('TIN', models.CharField(blank=True, max_length=100, verbose_name='ИНН')),
                ('bank', models.CharField(blank=True, max_length=100, verbose_name='Название Банка')),
                ('BIC', models.CharField(blank=True, max_length=100, verbose_name='БИК')),
                ('correspondent_account', models.CharField(blank=True, max_length=100, verbose_name='Корреспондентский счёт')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Реквизиты',
                'verbose_name_plural': 'Реквизиты',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('work_schedule', models.CharField(blank=True, max_length=255, verbose_name='График работы')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='employee', verbose_name='Фото')),
                ('name', models.TextField(max_length=50, verbose_name='ФИО')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('order', models.IntegerField(default=1, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Сотрудник компании',
                'verbose_name_plural': 'Сотрудники компании',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение/вопрос')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='logo', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': "Клиенты (блок 'Нас выбирают')",
                'verbose_name_plural': "Клиенты (блок 'Нас выбирают')",
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос-Ответ',
                'verbose_name_plural': 'Вопросы-Ответы',
            },
        ),
        migrations.CreateModel(
            name='ScopeServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название сферы услуг')),
            ],
            options={
                'verbose_name': 'Услуги для карусели',
                'verbose_name_plural': 'Услуги для карусели',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название услуги')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True, verbose_name='URL')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('time_work', models.CharField(max_length=150, verbose_name='Часы работы')),
                ('square', models.CharField(max_length=150, verbose_name='Площадь работы')),
                ('order', models.IntegerField(default=1, verbose_name='порядок')),
                ('is_popular', models.BooleanField(default=True, help_text='Отображать тег "Хит" или нет', verbose_name='Хит?')),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='services', verbose_name='Фото')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название соцсети')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на соцсеть')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.CreateModel(
            name='ServiceInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='pages.services', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Что входит в услугу',
                'verbose_name_plural': 'Что входит в услугу',
            },
        ),
    ]
