# Generated by Django 5.2.1 on 2026-02-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalservices',
            options={'verbose_name': 'Услуги дополнительные', 'verbose_name_plural': 'Услуги дополнительные'},
        ),
        migrations.AddField(
            model_name='aboutmain',
            name='cnt_cleaners',
            field=models.CharField(default=50, max_length=50, verbose_name='Кол-во клинеров'),
        ),
        migrations.AddField(
            model_name='aboutmain',
            name='cnt_managers',
            field=models.CharField(default=50, max_length=50, verbose_name='Кол-во менеджеров'),
        ),
        migrations.AlterField(
            model_name='aboutmain',
            name='cnt_people',
            field=models.CharField(default=50, max_length=50, verbose_name='Кол-во человек в команде'),
        ),
        migrations.AlterField(
            model_name='aboutmain',
            name='cnt_square',
            field=models.CharField(default=20, max_length=50, verbose_name='Кол-во тыс. кв.метров чистки'),
        ),
        migrations.AlterField(
            model_name='aboutmain',
            name='cnt_year',
            field=models.CharField(default=5, max_length=50, verbose_name='Кол-во лет работы в сфере'),
        ),
    ]
