# Generated by Django 5.2.1 on 2026-02-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_additionalservices_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='aboutmain',
            name='cnt_cleaners',
            field=models.CharField(default=20, max_length=50, verbose_name='Кол-во клинеров'),
        ),
        migrations.AlterField(
            model_name='aboutmain',
            name='cnt_managers',
            field=models.CharField(default=7, max_length=50, verbose_name='Кол-во менеджеров'),
        ),
        migrations.AlterField(
            model_name='aboutmain',
            name='cnt_order',
            field=models.IntegerField(default='8300', verbose_name='Кол-во выполненных заказов'),
        ),
        migrations.AlterField(
            model_name='aboutmain',
            name='cnt_year',
            field=models.CharField(default=20, max_length=50, verbose_name='Кол-во лет работы в сфере'),
        ),
    ]
