# Generated by Django 5.2.1 on 2025-07-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название соцсети')),
                ('url', models.URLField(verbose_name='Ссылка на соцсеть')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
