# Generated by Django 5.2.1 on 2025-07-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_socialnetwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на соцсеть'),
        ),
    ]
