# Generated by Django 5.2.1 on 2025-07-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_socialnetwork_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='color',
            field=models.CharField(default=1, max_length=50, verbose_name='Цвет)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='gradient',
            field=models.CharField(default=1, max_length=50, verbose_name='Градиент (linear-gradient(0deg, #53647A, #53647A), rgba(83, 100, 122, 0.4) 55%, rgba(0, 96, 223, 0.4) 100%);)'),
            preserve_default=False,
        ),
    ]
