# Generated by Django 5.2.1 on 2025-07-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_services_color_services_gradient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='gradient',
            field=models.TextField(verbose_name='Градиент (linear-gradient(0deg, #53647A, #53647A), rgba(83, 100, 122, 0.4) 55%, rgba(0, 96, 223, 0.4) 100%);)'),
        ),
    ]
