# Generated by Django 5.2.1 on 2025-07-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_services_gradient'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='order',
            field=models.IntegerField(default=1, verbose_name='порядок'),
            preserve_default=False,
        ),
    ]
