# Generated by Django 5.2.1 on 2025-10-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_services_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="employee",
            name="experience",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Стаж"
            ),
        ),
    ]
