# Generated by Django 5.2.1 on 2025-10-16 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_employee_description_employee_experience"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="services",
            name="price",
        ),
    ]
