# Generated by Django 5.2.1 on 2025-10-16 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0012_remove_services_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceInclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inclusions",
                        to="pages.services",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Что входит в услугу",
                "verbose_name_plural": "Что входит в услугу",
            },
        ),
    ]
