# Generated by Django 5.2.1 on 2025-10-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_serviceinclusion"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PriceServices",
        ),
    ]
