# Generated by Django 5.2.1 on 2025-10-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0014_delete_priceservices"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calc_account",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Расчётный счёт"
                    ),
                ),
                (
                    "TIN",
                    models.CharField(blank=True, max_length=100, verbose_name="ИНН"),
                ),
                (
                    "bank",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Название Банка"
                    ),
                ),
                (
                    "BIC",
                    models.CharField(blank=True, max_length=100, verbose_name="БИК"),
                ),
                (
                    "correspondent_account",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Корреспондентский счёт",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Наименование"
                    ),
                ),
            ],
            options={
                "verbose_name": "Реквизиты",
                "verbose_name_plural": "Реквизиты",
            },
        ),
        migrations.AddField(
            model_name="contact",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Город"),
        ),
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Электронная почта"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="work_schedule",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="График работы"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(blank=True, max_length=50, verbose_name="Телефон"),
        ),
    ]
