# Generated by Django 5.2.1 on 2025-10-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0015_companydetails_contact_city_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="slug",
            field=models.SlugField(max_length=255, null=True, verbose_name='URL'),
        ),
    ]
