# Generated by Django 5.2.1 on 2025-10-17 14:36

from django.db import migrations
from slugify import slugify

def populate_slugs(apps, schema_editor):
    Services = apps.get_model('pages', 'Services')
    for service in Services.objects.all():
        base_slug = slugify(service.scope.name)
        slug = base_slug
        counter = 1
        while Services.objects.exclude(pk=service.pk).filter(slug=slug).exists():
            slug = f'{base_slug}-{counter}'
            counter += 1
        service.slug = slug
        service.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_services_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs),
    ]