# Generated by Django 5.2.1 on 2025-10-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_services_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutmain',
            options={'verbose_name': 'Информация о компании', 'verbose_name_plural': 'Информация о компании'},
        ),
        migrations.AddField(
            model_name='aboutmain',
            name='cnt_reviews',
            field=models.CharField(default='25 000', help_text="Число на странице 'О компании' в подзаголовке 'довольными остались свыше 25 000 человек!'", max_length=50, verbose_name='Кол-во положительных отзывов'),
        ),
        migrations.AlterField(
            model_name='services',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='services',
            name='gradient',
            field=models.TextField(help_text='linear-gradient(0deg, #53647A, #53647A), rgba(83, 100, 122, 0.4) 55%, rgba(0, 96, 223, 0.4) 100%);', verbose_name='Градиент'),
        ),
        migrations.AlterField(
            model_name='services',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
