# Generated by Django 5.2.1 on 2025-10-21 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_alter_aboutmain_options_aboutmain_cnt_reviews_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(max_length=150, verbose_name='Описание дополнительной услуги')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.scopeservices', verbose_name='Сфера')),
            ],
            options={
                'verbose_name': 'Дополнительная услуга',
                'verbose_name_plural': 'Дополнительные услуги',
            },
        ),
    ]
