# Generated by Django 5.2.1 on 2025-10-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_additionalservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='color',
        ),
        migrations.AlterField(
            model_name='services',
            name='gradient',
            field=models.TextField(help_text='От светлого к темному: gradient-1, gradient-2, gradient-3, gradient-4', verbose_name='Градиент'),
        ),
    ]
