# Generated by Django 5.2.1 on 2025-10-31 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_remove_services_color_alter_services_gradient'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='videomain',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='services',
            name='gradient',
            field=models.TextField(help_text='От светлого к темному: gradient-1, gradient-2, gradient-3, gradient-4', verbose_name='Цвет карточки'),
        ),
        migrations.AlterField(
            model_name='services',
            name='order',
            field=models.IntegerField(default=1, verbose_name='порядок'),
        ),
    ]
