# Generated by Django 5.2.1 on 2025-10-31 04:34

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_employee_order_videomain_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='photos',
        ),
        migrations.AddField(
            model_name='services',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='services', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='services',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.DeleteModel(
            name='ServicePhoto',
        ),
    ]
