# Generated by Django 5.2.1 on 2026-02-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_remove_services_photos_services_photo_services_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='gradient',
        ),
        migrations.AddField(
            model_name='services',
            name='is_popular',
            field=models.BooleanField(default=True, help_text='Отображать тег "Хит" или нет', verbose_name='Хит?'),
        ),
    ]
