# Generated by Django 5.2.1 on 2026-02-03 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_remove_services_gradient_services_is_popular'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
